# Generated by Django 3.1 on 2020-11-08 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, unique=True)),
                ('client', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department', models.CharField(choices=[('PAINT', 'Paint'), ('MATCH', 'Match'), ('ROTO', 'Roto'), ('COMP', 'Comp'), ('3D', '3-d'), ('FX', 'Fx')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('YTS', 'Yet to Start'), ('WIP', 'Work in Progress'), ('FIN', 'Final')], max_length=50, null=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=300)),
                ('cut_in', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cut_out', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cut_frames', models.DecimalField(decimal_places=2, max_digits=9)),
                ('client_bid', models.DurationField()),
                ('client_duedate', models.DateField()),
                ('status', models.CharField(choices=[('YTS', 'Yet to Start'), ('WIP', 'Work in Progress'), ('FIN', 'Final'), ('FEED', 'Correction'), ('REVW', 'Review'), ('APPRVD', 'Approved'), ('HLD', 'Hold'), ('TB', 'Taken Back')], max_length=50)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='projects.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('Bid', models.DurationField()),
                ('assigned_users', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('shots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projects.shot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'shots'), name='unique_task_forshot'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('sequence', 'shot_name'), name='unique_shot_for_project'),
        ),
    ]
